<?php

namespace Societe\gestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ssRepository extends EntityRepository
{
	public function getByName(){
			
	}
}
